server:
   port: 8071
# MySql #
# spring.jpa.hibernate.ddl-auto=update
spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/db_cineapp?useSSL=true
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    
# Server Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8879/eureka

# Endpoints exposition
management:
  endpoints:
    web:
     exposure:
       include: "*"
     health:
       show-details: always
